### PR TITLE
#26 mentor-page changes

### PR DESCRIPTION
**Pull request by msramesh2k1**
Hey @adityathakurxd I had made changes on mentor page , Please do validate

### CODE REVIEW

**Comment by adityathakurxd** [comment]
Hey, @msramesh2k1 Could you attach a screenshot or video of changes? 
That'll help me review and merge this quicker. 🙌

**Comment by msramesh2k1** [comment]
Yeah Sure, Here I attached Screenshots,  do check

WhatsApp Image 2021-10-02 at 12 11 14 PM (1)
WhatsApp Image 2021-10-02 at 12 11 14 PM

**Review by adityathakurxd — APPROVED** [review]
Thank you @msramesh2k1! Looks good to merge 🎉

**Comment by adityathakurxd** [comment]
### Thank you so much for your contribution! 
We'd love to build and ship this project so it can be used by students across universities.

**Please do star the repository** 🌟 and, if possible share your story to LinkedIn and feel free to tag me. (@adityathakurxd)
Thank you again. Have a great journey in Open Source! @msramesh2k1

**Comment by msramesh2k1** [comment]
> Thank you @msramesh2k1! Looks good to merge 🎉

cool

**Pull request merged**
