### PR TITLE
mentor preview widget

### PR DESCRIPTION
**Pull request by palak296**

### CODE REVIEW

**Comment by palak296** [comment]
please suggest edits.

**Comment by adityathakurxd** [comment]
Could you attach a screenshot if you have of the widget?

**Review by adityathakurxd — APPROVED** [review]
Looks good to merge! Great work @palak296 🌟
Just attach a screenshot if possible, otherwise, I'll merge. 🙌

**Comment by adityathakurxd** [comment]
### Thank you so much for your contribution! 
We'd love to build and ship this project so it can be used by students across universities.

**Please do star the repository** 🌟 and, if possible share your story to LinkedIn and feel free to tag me. (@adityathakurxd)
Thank you again. Have a great journey in Open Source!

**Comment by palak296** [comment]
https://user-images.githubusercontent.com/74818938/135583581-86242c75-1e32-4812-8e2a-acbef1b8e750.mp4

**Comment by adityathakurxd** [comment]
Thank you! LGTM

**Pull request merged**
